### ISSUE TITLE
Atari clone with ps/2

### ISSUE THREAD

**Issue by ps68060** [ChrisDeadman/usb-to-ps2-gameport-hat#1]
I am a newcomer to Arduino but I have been looking for a way to connect USB mouse (wireless) to an Atari clone that has ps/2 sockets only. https://uweschneider.de/en/projects_milan.php

I found your archived project https://github.com/ChrisDeadman/Usb2Ps2Mouse  which looks ideal but then I saw this project and wondered if it is the better solution.

Hardware is not my area so I want to keep that to a minimum.

**Comment by ChrisDeadman** [comment]
Hi!
The mouse code of both projects should be pretty equal, I rechecked and do not see that I had to fix anything afterwards.
You can use either but I would recommend this project (you do not need to use the PCB from this project, it is only needed for gameport support and has the PS/2 connector soldered)
You can change the pins for the PS/2 output in https://github.com/ChrisDeadman/usb-to-ps2-gameport-hat/blob/master/Software/usb-to-ps2-gameport-hat/include/Config.h

**Comment by ChrisDeadman** [comment]
fyi: make sure to use a level-converter from 3.3V to 5V for the PS/2 connector like in the picture of the Usb2Ps2Mouse, I ordered those and they work well for prototyping https://www.amazon.de/gp/product/B07F3P942R

**Comment by ChrisDeadman** [comment]
> Hardware is not my area so I want to keep that to a minimum.

I added an image of the schematic now so it can be seen which pins are PS2_DATA1 and PS2_CLOCK1, how they are connected to level-converter and from there to the PS/2 connector.
