### ISSUE TITLE
Keyboard Support Feature Request

### ISSUE THREAD

**Issue by Ulfenknulfen** [ChrisDeadman/usb-to-ps2-gameport-hat#2]
Hi Chris. That's a super amazing Project for Retro-PC's!

Is Keyboard support comming in the next time?

best regards
Paddy

**Comment by ChrisDeadman** [comment]
Hey @Ulfenknulfen!

Thanks for your interest in the project! 
Keyboard support really is something I wanted to add for years now but unfortunately I haven't had much time lately for my retro projects :disappointed: 
If I ever get back to it I will add it but that won't be in the near future :/

In case someone else wants to contribute I should find time tho to review pull requests and give some pointers.

**Comment by DaveSmith1985** [comment]
With Keyboard Support (for logitech usb that have keyb and mouse...) this project will be awesome!

**Comment by Ulfenknulfen** [comment]
Hi Dave and Chris.

Yes this IS an awesome Project for every Retro-PC. But i think there's a small mistake in kicad Project...
PS/2 Pin 4 must be 5V, i think.




best regards
Paddy

**Comment by ChrisDeadman** [comment]
Damn, how could I miss that - actually not that small of a mistake 😆
Seems the mouse I used for testing powered itself over the data line 😀
In your zip it's fixed for the PCB but not in the schematic, I will fix it in the schematic as well then push fix.
Thanks for finding it!

**Comment by Ulfenknulfen** [comment]
No Problem.

you can also checkout and use my new kicad file - i did some 
improvements.

best regards and have a nice X-Mas :-)
Paddy

[kicad.zip](https://github.com/ChrisDeadman/usb-to-ps2-gameport-hat/files/13725405/kicad.zip)

**Comment by Ulfenknulfen** [comment]
Hi Chris.

It has nothing to do with USB Functionality. It's just for deliver 5V to the Circuit.
Some users have no Gameport, and want just use it for Keyboard/Mouse... .

best regards
Paddy

Feel free to use the files!
Edit: new File below

**Comment by ChrisDeadman** [comment]
This is the connection to the PC and the PS/2 cannot really deliver enough current that is why I did not connect it initially.
The intention was that you either get power from Gameport (which is not recommended since it can also not deliver much current) or via USB. That is why there is a USB connector on the board, it's purely for power-delivery.

**Comment by Ulfenknulfen** [comment]
Hi Chris. 

Yes, that makes perfect sense, of course! 
I don't want to be annoying, but is there anything new about Keyboard support?

best regards
Paddy

**Comment by ChrisDeadman** [comment]
I don't think I will have time over the holidays for it, also I need to order new PCB first, the one I have is old version only has 1 PS/2 port, never ordered the current version ^^

**Comment by Ulfenknulfen** [comment]
I Order PCB too, but i dont need all 5 of them.

Where are you from? Germany?

 

Best regards

Paddy

 

Von: Christopher Hubmann ***@***.***> 
Gesendet: Mittwoch, 20. Dezember 2023 13:52
An: ChrisDeadman/usb-to-ps2-gameport-hat ***@***.***>
Cc: Patrick Bonner ***@***.***>; Mention ***@***.***>
Betreff: Re: [ChrisDeadman/usb-to-ps2-gameport-hat] Keyboard Support Feature Request (Issue #2)

 

I don't think I will have time over the holidays for it, also I need to order new PCB first, the one I have is old version only has 1 PS/2 port, never ordered the current version ^^ Maybe I have time for it summer 2024 but I cannot promise anything, sorry 😕

**Comment by Ulfenknulfen** [comment]
I will Order PCB's too, but i don't need all 5 of them.

Where are you from? Germany?



Best regards

Paddy
P.S. i did some optimizations. Here's the actual File:
edit 12.23.2023 - File sent via Email.

**Comment by ChrisDeadman** [comment]
I will have a look next week to compare the changes.
Btw. it would help a lot if you fork the project and make pull request if you have time at some point, so much easier to compare changes and comment instead of just this issue.

Thanks for your contribution, it means a lot because I really didn't have much time and I really appreciate if this project is finally used by someone else than just me 🙂

**Comment by Ulfenknulfen** [comment]
i did ;-)

here the actual Version

[usb_to_ps2_gameport-hat_1.3.zip](https://github.com/ChrisDeadman/usb-to-ps2-gameport-hat/files/13800757/usb_to_ps2_gameport-hat_1.3.zip)



best regards
paddy

**Comment by ChrisDeadman** [comment]
Thanks @Ulfenknulfen for your help with this Pull Request!
After some testing we now have a good initial version I would say 🙂

**Comment by Ulfenknulfen** [comment]
It was a honor to work on this Project!

best reagrds
Paddy
